version: '1'
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_WRITE_PASSWORD}"
      MYSQL_DATABASE: "${DB_WRITE_DATABASE}"
      # MYSQL_USER: "${DB_WRITE_USER}"
      MYSQL_PASSWORD: "${DB_WRITE_PASSWORD}"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: